### PR TITLE
Update to -m (Adding mount points)

### LINKED ISSUE #41: -m flag can't handle multiple directories
I'm using Docker version 17.12.1-ce, build 7390fc6 on an Ubuntu 18.04 system. When I try to use -m with multiple directories, docker2singularity doesn't deal with the space in the -m string correctly. Note that it creates a directory "foo ".

It looks like the the "adding mount points" part of docker2singularity.sh changed at some point.  

```
paciorek@shelob:~/staff/projects/docker-test/mpi> docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/output --privileged -t --rm    singularityware/docker2singularity -m "/foo /bar" ubuntu:18.04
Image Format: squashfs
Docker Image: ubuntu:18.04

Inspected Size: 85 MB

(1/10) Creating a build sandbox...
(2/10) Exporting filesystem...
(3/10) Creating labels...
(4/10) Adding run script...
(5/10) Setting ENV variables...
(6/10) Adding mount points...
(7/10) Fixing permissions...
(8/10) Stopping and removing the container...
(9/10) Building squashfs container...
Building image from sandbox: /tmp/ubuntu_18.04-2018-09-05-5ecea5d81788.build
Building Singularity image...
Singularity container built: /tmp/ubuntu_18.04-2018-09-05-5ecea5d81788.simg
Cleaning up...
(10/10) Moving the image to the output folder...
     27,947,039 100%  369.74MB/s    0:00:00 (xfr#1, to-chk=0/1)
Final Size: 27MB
paciorek@shelob:~/staff/projects/docker-test/mpi> singularity shell /tmp/ubuntu_18.04-2018-09-05-5ecea5d81788.simg
Singularity: Invoking an interactive shell within container...

Singularity ubuntu_18.04-2018-09-05-5ecea5d81788.simg:~/staff/projects/docker-test/mpi> ls /
 accounts   boot   environment	'foo '	 lib	 media	 opt    root   sbin	     singularity.json   sys   usr
 bin	    dev    etc		 home	 lib64	 mnt	 proc   run    singularity   srv	        tmp   var
```

If I simply start a Docker container using the docker2singularity image, and try to run the mkdir -p line from docker2singularity.sh, I essentially recreate the issue; 'foo bar' is a single directory here:

```
paciorek@shelob:~/staff/projects/docker-test/mpi> docker run -it --rm --entrypoint "/bin/bash" singularityware/docker2singularity
bash-4.3# mount_points="foo bar"
bash-4.3# new_container_name=/tmp/blah.id
bash-4.3# build_sandbox="${new_container_name}.build"
bash-4.3# echo ${build_sandbox}
/tmp/blah.id.build
bash-4.3# mkdir -p "${build_sandbox}/${mount_points}"
bash-4.3# ls /tmp/blah.id.build/
foo bar
```

### PR DESCRIPTION
**Pull request by kasbohm**
Attempt to resolve #41

### CODE REVIEW

**Comment by vsoch** [comment]
hey @kasbohm sorry I missed this - I wasn't watching the repo! I'd like to suggest that I put in an updated (version 3.+ family) branch and then we address your issue there. The master was never updated to latest, mostly because I was keeping it constant for a particular user base still using the 2.x family, but that's not the best way to proceed I think.

**Comment by vsoch** [comment]
hey @kasbohm I think this looks good - I just turned on building forked pull requests on circle (not sure why it was off) if you want to try a trivial commit/push to see if it triggers again. I'd also suggest we get this fix into the other branches.

**Comment by vsoch** [comment]
heya again @kasbohm - I got the fix in for you here:

https://github.com/singularityware/docker2singularity/blob/master/docker2singularity.sh#L290

if it looks good, feel free to close this PR. Apologies again for missing your contribution - I'll be updating latest (master) to the newest singularity likely tomorrow, and your feedback / help will be appreciated!

**Comment by kasbohm** [comment]
Hi @vsoch, thanks a lot for picking this up again! I added a small commit to the branch, and it seems to hae triggered the build. Closing.

**Pull request closed without merging**
