### PR TITLE
Remove scripts/env/10-docker2singularity.sh

### PR DESCRIPTION
**Pull request by nathanweeks**
Fixes https://github.com/singularityware/docker2singularity/issues/62

### CODE REVIEW

**Comment by vsoch** [comment]
Wait, does this address the missing entrypoint issue?

**Comment by nathanweeks** [comment]
Only the original issue reported in https://github.com/singularityware/docker2singularity/issues/62 (which I guess now documents two distinct issues). Did you want the entrypoint issue to be fixed first?

**Comment by vsoch** [comment]
We want the container here to build cleanly without any issue - are you able to build and then run without any problem? Sorry I'm working on a million things at once right now, I feel a little tired :P

**Comment by nathanweeks** [comment]
I completely understand (and can relate)! I'll plan on taking a look at the entrypoint issue tomorrow.

**Comment by vsoch** [comment]
okay cool, let's sync up tomorrow!

**Comment by nathanweeks** [comment]
OK, I think I fixed the ENTRYPOINT issue as well. docker-entrypoint.sh was getting left behind in the "docker" image by the new multi-stage build. Since the docker client is needed in the container image, and since docker:18.09 is based on alpine anyway, I thought it might be easiest to use docker as the base image instead of alpine, and sprinkle on bash, python, and rsync as dependencies for docker2singularity.sh.

The resulting image for v3.2.1 is ~1/3 the size of v3.1.

**Comment by vsoch** [comment]
Ah good catch! I totally missed that. Good call on using the latest docker tag (confirmed [here](https://hub.docker.com/_/docker)) and if you've confirmed it's working, I'm good to update the branch. What I think we should do after this is update the master branch to be this latest. I don't trust Docker Hub so much anymore, so likely I'll build and push the container locally. Should I try the build before we merge and move on to next step wrt the master branch?

**Comment by vsoch** [comment]
Since we know the current branch is broken, and you've confirmed good here, I'm going to merge and test. If everything is okay I'll open PR for this branch to master.

**Comment by nathanweeks** [comment]
Hi @vsoch , that workflow sounds good to me. Please let me know if/when there's anything else I can help with.

**Comment by vsoch** [comment]
I think we are good! And I forgot that I already had written the circle recipe to handle deployments, so updating the v3.2.1 and master branches is all we needed to do :) Let me know if you run into any issues, and otherwise, huge thanks for this catch! I remember I started working on it and... just totally forgot :P

**Pull request merged**
