### PR TITLE
Added support for docker's WORKDIR and updated singularity's url

### PR DESCRIPTION
**Pull request by pierlauro**
- Change folder to docker container's working directory before executing the entrypoint
- Updated singularity's url in the Dockerfile (previous one not reachable anymore)

### CODE REVIEW

**Comment by vsoch** [comment]
heyo @pierlauro ! This is a very important feature, but I think it belongs with singularity proper - e.g., if there is a final WORKDIR in the container it should be honored by the container natively. Would you be able to open an issue on the singularity repository to suggest this?

**Comment by vsoch** [comment]
@pierlauro see this issue --> https://github.com/sylabs/singularity/issues/380 please comment here if you think Singularity should honor `WORKDIR`.

**Comment by pierlauro** [comment]
> [sylabs/singularity#380](https://github.com/sylabs/singularity/issues/380)

I think Singularity should provide a `WORKDIR` feature similar to docker, I added my considerations in the cited issue.

I just adapted and tested the PR to be merged after the new commits in the master.

**Comment by vsoch** [comment]
Since you didn't bring the issue back here and merged in another repo, closing this issue.

**Pull request closed without merging**
