### PR TITLE
Allow empty mount_points

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by chrisfilo** [comment]
Happy to merge, but curious in what use case is it necessary?

**Comment by pditommaso** [comment]
Currently when the `-m` option is not specified some [default mount](https://github.com/singularityware/docker2singularity/blob/master/docker2singularity.sh#L23) points are defined.

This patch allows me suppress the creation of that mounts that are not required in my environment.

**Comment by chrisfilo** [comment]
Oh, I understand what it does (and I'm happy to merge it), but I was wondering what is the use case in which creation of default set of mount points would be detrimental.

**Comment by pditommaso** [comment]
Well, unused mount points are not harmful in principle. But I would like to avoid that just for consistency of the target container image.

**Pull request merged**
